### ISSUE TITLE
MeanMax

### ISSUE THREAD

**Issue by csj** [dreignier/cg-brutaltester#8]
Hi, two questions:
* will the MeanMax referee be available when the contest is opened?
* if yes, will it work with this utility directly?

Thanks

**Comment by KevinBusse** [comment]
I only had little time so far, and had no real time for tests, but you might give https://github.com/KevinBusse/cg-referee-mean-max a try

**Comment by Gulzt** [comment]
@KevinBusse With this commit: *First attempt to support 3 players*, I run into the following problem:
```
java.util.NoSuchElementException: No line found
	at java.util.Scanner.nextLine(Scanner.java:1540) ~[?:1.8.0_151]
	at com.magusgeek.brutaltester.GameThread.run(GameThread.java:102) [brutaltester.jar:?]
```

However, the commit before didn't crash. Just all games resulted in 0.00% for all players.

Any ideas? I run it with the following command:
`java -jar brutaltester.jar -r "java -jar cg-mm.jar" -p1 "./temp.exe" -p2 "./temp.exe" -p3 "./temp.exe" -t 3 -n 10 -l "./logs/"`

**Comment by KevinBusse** [comment]
Thanks to @Emerion a first release can now be found under: https://github.com/KevinBusse/cg-referee-mean-max/releases
